/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeSources;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdgeSourcesRecord extends TableRecordImpl<EdgeSourcesRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1843190854;

    /**
     * Setter for <code>public.edge_sources.edge_id</code>.
     */
    public void setEdgeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.edge_sources.edge_id</code>.
     */
    public Integer getEdgeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.edge_sources.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.edge_sources.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EdgeSources.EDGE_SOURCES.EDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EdgeSources.EDGE_SOURCES.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeSourcesRecord value1(Integer value) {
        setEdgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeSourcesRecord value2(Integer value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeSourcesRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EdgeSourcesRecord
     */
    public EdgeSourcesRecord() {
        super(EdgeSources.EDGE_SOURCES);
    }

    /**
     * Create a detached, initialised EdgeSourcesRecord
     */
    public EdgeSourcesRecord(Integer edgeId, Integer sourceId) {
        super(EdgeSources.EDGE_SOURCES);

        set(0, edgeId);
        set(1, sourceId);
    }
}
