/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeFeatures;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdgeFeaturesRecord extends TableRecordImpl<EdgeFeaturesRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -769774647;

    /**
     * Setter for <code>public.edge_features.rel_id</code>.
     */
    public void setRelId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.edge_features.rel_id</code>.
     */
    public Integer getRelId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.edge_features.direction</code>.
     */
    public void setDirection(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.edge_features.direction</code>.
     */
    public Integer getDirection() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.edge_features.node_id</code>.
     */
    public void setNodeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.edge_features.node_id</code>.
     */
    public Integer getNodeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.edge_features.edge_id</code>.
     */
    public void setEdgeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.edge_features.edge_id</code>.
     */
    public Integer getEdgeId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EdgeFeatures.EDGE_FEATURES.REL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EdgeFeatures.EDGE_FEATURES.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return EdgeFeatures.EDGE_FEATURES.NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return EdgeFeatures.EDGE_FEATURES.EDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeFeaturesRecord value1(Integer value) {
        setRelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeFeaturesRecord value2(Integer value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeFeaturesRecord value3(Integer value) {
        setNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeFeaturesRecord value4(Integer value) {
        setEdgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdgeFeaturesRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EdgeFeaturesRecord
     */
    public EdgeFeaturesRecord() {
        super(EdgeFeatures.EDGE_FEATURES);
    }

    /**
     * Create a detached, initialised EdgeFeaturesRecord
     */
    public EdgeFeaturesRecord(Integer relId, Integer direction, Integer nodeId, Integer edgeId) {
        super(EdgeFeatures.EDGE_FEATURES);

        set(0, relId);
        set(1, direction);
        set(2, nodeId);
        set(3, edgeId);
    }
}
