/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.RankedFeatures;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RankedFeaturesRecord extends TableRecordImpl<RankedFeaturesRecord> implements Record6<Integer, Integer, Integer, Integer, Float, Long> {

    private static final long serialVersionUID = -261146905;

    /**
     * Setter for <code>public.ranked_features.rel_id</code>.
     */
    public void setRelId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ranked_features.rel_id</code>.
     */
    public Integer getRelId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ranked_features.direction</code>.
     */
    public void setDirection(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ranked_features.direction</code>.
     */
    public Integer getDirection() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ranked_features.node_id</code>.
     */
    public void setNodeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ranked_features.node_id</code>.
     */
    public Integer getNodeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ranked_features.edge_id</code>.
     */
    public void setEdgeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ranked_features.edge_id</code>.
     */
    public Integer getEdgeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.ranked_features.weight</code>.
     */
    public void setWeight(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ranked_features.weight</code>.
     */
    public Float getWeight() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>public.ranked_features.rank</code>.
     */
    public void setRank(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ranked_features.rank</code>.
     */
    public Long getRank() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Float, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Float, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RankedFeatures.RANKED_FEATURES.REL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RankedFeatures.RANKED_FEATURES.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RankedFeatures.RANKED_FEATURES.NODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RankedFeatures.RANKED_FEATURES.EDGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return RankedFeatures.RANKED_FEATURES.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return RankedFeatures.RANKED_FEATURES.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component5() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEdgeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value1(Integer value) {
        setRelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value2(Integer value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value3(Integer value) {
        setNodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value4(Integer value) {
        setEdgeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value5(Float value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord value6(Long value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankedFeaturesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Float value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RankedFeaturesRecord
     */
    public RankedFeaturesRecord() {
        super(RankedFeatures.RANKED_FEATURES);
    }

    /**
     * Create a detached, initialised RankedFeaturesRecord
     */
    public RankedFeaturesRecord(Integer relId, Integer direction, Integer nodeId, Integer edgeId, Float weight, Long rank) {
        super(RankedFeatures.RANKED_FEATURES);

        set(0, relId);
        set(1, direction);
        set(2, nodeId);
        set(3, edgeId);
        set(4, weight);
        set(5, rank);
    }
}
