/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.ufl.aida.ta2.tables.MentionsForUpdate;
import org.ufl.aida.ta2.tables.Tuples;
import org.ufl.aida.ta2.tables.Tuples2;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_MENTIONS_FOR_UPDATE = Indexes0.PK_MENTIONS_FOR_UPDATE;
    public static final Index PK_TUPLES = Indexes0.PK_TUPLES;
    public static final Index TUPLES2_MID_IDX = Indexes0.TUPLES2_MID_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_MENTIONS_FOR_UPDATE = Internal.createIndex("pk_mentions_for_update", MentionsForUpdate.MENTIONS_FOR_UPDATE, new OrderField[] { MentionsForUpdate.MENTIONS_FOR_UPDATE.AMID }, true);
        public static Index PK_TUPLES = Internal.createIndex("pk_tuples", Tuples.TUPLES, new OrderField[] { Tuples.TUPLES.MID }, true);
        public static Index TUPLES2_MID_IDX = Internal.createIndex("tuples2_mid_idx", Tuples2.TUPLES2, new OrderField[] { Tuples2.TUPLES2.MID }, true);
    }
}
