/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.daos;


import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.ufl.aida.ta2.tables.MentionsForUpdate;
import org.ufl.aida.ta2.tables.records.MentionsForUpdateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MentionsForUpdateDao extends DAOImpl<MentionsForUpdateRecord, org.ufl.aida.ta2.tables.pojos.MentionsForUpdate, String> {

    /**
     * Create a new MentionsForUpdateDao without any configuration
     */
    public MentionsForUpdateDao() {
        super(MentionsForUpdate.MENTIONS_FOR_UPDATE, org.ufl.aida.ta2.tables.pojos.MentionsForUpdate.class);
    }

    /**
     * Create a new MentionsForUpdateDao with an attached configuration
     */
    public MentionsForUpdateDao(Configuration configuration) {
        super(MentionsForUpdate.MENTIONS_FOR_UPDATE, org.ufl.aida.ta2.tables.pojos.MentionsForUpdate.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(org.ufl.aida.ta2.tables.pojos.MentionsForUpdate object) {
        return object.getAmid();
    }

    /**
     * Fetch records that have <code>amid IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByAmid(String... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.AMID, values);
    }

    /**
     * Fetch a unique record that has <code>amid = value</code>
     */
    public org.ufl.aida.ta2.tables.pojos.MentionsForUpdate fetchOneByAmid(String value) {
        return fetchOne(MentionsForUpdate.MENTIONS_FOR_UPDATE.AMID, value);
    }

    /**
     * Fetch records that have <code>atype IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByAtype(String... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.ATYPE, values);
    }

    /**
     * Fetch records that have <code>acid IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByAcid(String... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.ACID, values);
    }

    /**
     * Fetch records that have <code>strings IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByStrings(String[]... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.STRINGS, values);
    }

    /**
     * Fetch records that have <code>enstrings IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByEnstrings(String[]... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.ENSTRINGS, values);
    }

    /**
     * Fetch records that have <code>resolved_string IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByResolvedString(String... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.RESOLVED_STRING, values);
    }

    /**
     * Fetch records that have <code>resolved_score IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByResolvedScore(BigDecimal... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.RESOLVED_SCORE, values);
    }

    /**
     * Fetch records that have <code>fromfuzzymatching IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByFromfuzzymatching(Boolean... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.FROMFUZZYMATCHING, values);
    }

    /**
     * Fetch records that have <code>resolved_type IN (values)</code>
     */
    public List<org.ufl.aida.ta2.tables.pojos.MentionsForUpdate> fetchByResolvedType(String... values) {
        return fetch(MentionsForUpdate.MENTIONS_FOR_UPDATE.RESOLVED_TYPE, values);
    }
}
