/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IExpansions extends Serializable {

    /**
     * Setter for <code>public.expansions.eid</code>.
     */
    public void setEid(String... value);

    /**
     * Getter for <code>public.expansions.eid</code>.
     */
    public String[] getEid();

    /**
     * Setter for <code>public.expansions.type_event</code>.
     */
    public void setTypeEvent(String value);

    /**
     * Getter for <code>public.expansions.type_event</code>.
     */
    public String getTypeEvent();

    /**
     * Setter for <code>public.expansions.weight</code>.
     */
    public void setWeight(Double value);

    /**
     * Getter for <code>public.expansions.weight</code>.
     */
    public Double getWeight();

    /**
     * Setter for <code>public.expansions.arg1</code>.
     */
    public void setArg1(String... value);

    /**
     * Getter for <code>public.expansions.arg1</code>.
     */
    public String[] getArg1();

    /**
     * Setter for <code>public.expansions.arg2</code>.
     */
    public void setArg2(String... value);

    /**
     * Getter for <code>public.expansions.arg2</code>.
     */
    public String[] getArg2();

    /**
     * Setter for <code>public.expansions.arg3</code>.
     */
    public void setArg3(String... value);

    /**
     * Getter for <code>public.expansions.arg3</code>.
     */
    public String[] getArg3();

    /**
     * Setter for <code>public.expansions.arg4</code>.
     */
    public void setArg4(String... value);

    /**
     * Getter for <code>public.expansions.arg4</code>.
     */
    public String[] getArg4();

    /**
     * Setter for <code>public.expansions.arg5</code>.
     */
    public void setArg5(String... value);

    /**
     * Getter for <code>public.expansions.arg5</code>.
     */
    public String[] getArg5();

    /**
     * Setter for <code>public.expansions.arg6</code>.
     */
    public void setArg6(String... value);

    /**
     * Getter for <code>public.expansions.arg6</code>.
     */
    public String[] getArg6();

    /**
     * Setter for <code>public.expansions.arg7</code>.
     */
    public void setArg7(String... value);

    /**
     * Getter for <code>public.expansions.arg7</code>.
     */
    public String[] getArg7();

    /**
     * Setter for <code>public.expansions.bitmap_null</code>.
     */
    public void setBitmapNull(String value);

    /**
     * Getter for <code>public.expansions.bitmap_null</code>.
     */
    public String getBitmapNull();

    /**
     * Setter for <code>public.expansions.bitmap_neg</code>.
     */
    public void setBitmapNeg(String value);

    /**
     * Getter for <code>public.expansions.bitmap_neg</code>.
     */
    public String getBitmapNeg();

    /**
     * Setter for <code>public.expansions.bitmap_hed</code>.
     */
    public void setBitmapHed(String value);

    /**
     * Getter for <code>public.expansions.bitmap_hed</code>.
     */
    public String getBitmapHed();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IExpansions
     */
    public void from(IExpansions from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IExpansions
     */
    public <E extends IExpansions> E into(E into);
}
