/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITuples2 extends Serializable {

    /**
     * Setter for <code>public.tuples2.mid</code>.
     */
    public void setMid(String value);

    /**
     * Getter for <code>public.tuples2.mid</code>.
     */
    public String getMid();

    /**
     * Setter for <code>public.tuples2.nistType</code>.
     */
    public void setNisttype(String value);

    /**
     * Getter for <code>public.tuples2.nistType</code>.
     */
    public String getNisttype();

    /**
     * Setter for <code>public.tuples2.scoreEvent</code>.
     */
    public void setScoreevent(Double value);

    /**
     * Getter for <code>public.tuples2.scoreEvent</code>.
     */
    public Double getScoreevent();

    /**
     * Setter for <code>public.tuples2.negated</code>.
     */
    public void setNegated(Boolean value);

    /**
     * Getter for <code>public.tuples2.negated</code>.
     */
    public Boolean getNegated();

    /**
     * Setter for <code>public.tuples2.hedged</code>.
     */
    public void setHedged(Boolean value);

    /**
     * Getter for <code>public.tuples2.hedged</code>.
     */
    public Boolean getHedged();

    /**
     * Setter for <code>public.tuples2.constituent</code>.
     */
    public void setConstituent(String... value);

    /**
     * Getter for <code>public.tuples2.constituent</code>.
     */
    public String[] getConstituent();

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    public void setJsonObjectAgg(Object value);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    public Object getJsonObjectAgg();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITuples2
     */
    public void from(ITuples2 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITuples2
     */
    public <E extends ITuples2> E into(E into);
}
