/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entityresolver implements Serializable {

    private static final long serialVersionUID = -403998735;

    private String   handle;
    private String   category;
    private String   type;
    private String   subtype;
    private String[] attributes;
    private String[] attributes2;
    private String[] kbids;
    private String[] descriptions;
    private String[] justifications;
    private String[] textStrings;
    private String[] ids;
    private String[] mids;

    public Entityresolver() {}

    public Entityresolver(Entityresolver value) {
        this.handle = value.handle;
        this.category = value.category;
        this.type = value.type;
        this.subtype = value.subtype;
        this.attributes = value.attributes;
        this.attributes2 = value.attributes2;
        this.kbids = value.kbids;
        this.descriptions = value.descriptions;
        this.justifications = value.justifications;
        this.textStrings = value.textStrings;
        this.ids = value.ids;
        this.mids = value.mids;
    }

    public Entityresolver(
        String   handle,
        String   category,
        String   type,
        String   subtype,
        String[] attributes,
        String[] attributes2,
        String[] kbids,
        String[] descriptions,
        String[] justifications,
        String[] textStrings,
        String[] ids,
        String[] mids
    ) {
        this.handle = handle;
        this.category = category;
        this.type = type;
        this.subtype = subtype;
        this.attributes = attributes;
        this.attributes2 = attributes2;
        this.kbids = kbids;
        this.descriptions = descriptions;
        this.justifications = justifications;
        this.textStrings = textStrings;
        this.ids = ids;
        this.mids = mids;
    }

    public String getHandle() {
        return this.handle;
    }

    public void setHandle(String handle) {
        this.handle = handle;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSubtype() {
        return this.subtype;
    }

    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    public String[] getAttributes() {
        return this.attributes;
    }

    public void setAttributes(String... attributes) {
        this.attributes = attributes;
    }

    public String[] getAttributes2() {
        return this.attributes2;
    }

    public void setAttributes2(String... attributes2) {
        this.attributes2 = attributes2;
    }

    public String[] getKbids() {
        return this.kbids;
    }

    public void setKbids(String... kbids) {
        this.kbids = kbids;
    }

    public String[] getDescriptions() {
        return this.descriptions;
    }

    public void setDescriptions(String... descriptions) {
        this.descriptions = descriptions;
    }

    public String[] getJustifications() {
        return this.justifications;
    }

    public void setJustifications(String... justifications) {
        this.justifications = justifications;
    }

    public String[] getTextStrings() {
        return this.textStrings;
    }

    public void setTextStrings(String... textStrings) {
        this.textStrings = textStrings;
    }

    public String[] getIds() {
        return this.ids;
    }

    public void setIds(String... ids) {
        this.ids = ids;
    }

    public String[] getMids() {
        return this.mids;
    }

    public void setMids(String... mids) {
        this.mids = mids;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entityresolver (");

        sb.append(handle);
        sb.append(", ").append(category);
        sb.append(", ").append(type);
        sb.append(", ").append(subtype);
        sb.append(", ").append(Arrays.toString(attributes));
        sb.append(", ").append(Arrays.toString(attributes2));
        sb.append(", ").append(Arrays.toString(kbids));
        sb.append(", ").append(Arrays.toString(descriptions));
        sb.append(", ").append(Arrays.toString(justifications));
        sb.append(", ").append(Arrays.toString(textStrings));
        sb.append(", ").append(Arrays.toString(ids));
        sb.append(", ").append(Arrays.toString(mids));

        sb.append(")");
        return sb.toString();
    }
}
