/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdgeSources implements Serializable {

    private static final long serialVersionUID = 602942900;

    private Integer edgeId;
    private Integer sourceId;

    public EdgeSources() {}

    public EdgeSources(EdgeSources value) {
        this.edgeId = value.edgeId;
        this.sourceId = value.sourceId;
    }

    public EdgeSources(
        Integer edgeId,
        Integer sourceId
    ) {
        this.edgeId = edgeId;
        this.sourceId = sourceId;
    }

    public Integer getEdgeId() {
        return this.edgeId;
    }

    public void setEdgeId(Integer edgeId) {
        this.edgeId = edgeId;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EdgeSources (");

        sb.append(edgeId);
        sb.append(", ").append(sourceId);

        sb.append(")");
        return sb.toString();
    }
}
