/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdgeFeatures implements Serializable {

    private static final long serialVersionUID = 1934187864;

    private Integer relId;
    private Integer direction;
    private Integer nodeId;
    private Integer edgeId;

    public EdgeFeatures() {}

    public EdgeFeatures(EdgeFeatures value) {
        this.relId = value.relId;
        this.direction = value.direction;
        this.nodeId = value.nodeId;
        this.edgeId = value.edgeId;
    }

    public EdgeFeatures(
        Integer relId,
        Integer direction,
        Integer nodeId,
        Integer edgeId
    ) {
        this.relId = relId;
        this.direction = direction;
        this.nodeId = nodeId;
        this.edgeId = edgeId;
    }

    public Integer getRelId() {
        return this.relId;
    }

    public void setRelId(Integer relId) {
        this.relId = relId;
    }

    public Integer getDirection() {
        return this.direction;
    }

    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    public Integer getNodeId() {
        return this.nodeId;
    }

    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    public Integer getEdgeId() {
        return this.edgeId;
    }

    public void setEdgeId(Integer edgeId) {
        this.edgeId = edgeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EdgeFeatures (");

        sb.append(relId);
        sb.append(", ").append(direction);
        sb.append(", ").append(nodeId);
        sb.append(", ").append(edgeId);

        sb.append(")");
        return sb.toString();
    }
}
