/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sources implements Serializable {

    private static final long serialVersionUID = -1924869647;

    private Integer id;
    private String  uri;

    public Sources() {}

    public Sources(Sources value) {
        this.id = value.id;
        this.uri = value.uri;
    }

    public Sources(
        Integer id,
        String  uri
    ) {
        this.id = id;
        this.uri = uri;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sources (");

        sb.append(id);
        sb.append(", ").append(uri);

        sb.append(")");
        return sb.toString();
    }
}
