/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Edges implements Serializable {

    private static final long serialVersionUID = -1749294405;

    private Integer id;
    private String  uri;
    private Integer relationId;
    private Integer startId;
    private Integer endId;
    private Float   weight;
    private Object  data;

    public Edges() {}

    public Edges(Edges value) {
        this.id = value.id;
        this.uri = value.uri;
        this.relationId = value.relationId;
        this.startId = value.startId;
        this.endId = value.endId;
        this.weight = value.weight;
        this.data = value.data;
    }

    public Edges(
        Integer id,
        String  uri,
        Integer relationId,
        Integer startId,
        Integer endId,
        Float   weight,
        Object  data
    ) {
        this.id = id;
        this.uri = uri;
        this.relationId = relationId;
        this.startId = startId;
        this.endId = endId;
        this.weight = weight;
        this.data = data;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public Integer getRelationId() {
        return this.relationId;
    }

    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    public Integer getStartId() {
        return this.startId;
    }

    public void setStartId(Integer startId) {
        this.startId = startId;
    }

    public Integer getEndId() {
        return this.endId;
    }

    public void setEndId(Integer endId) {
        this.endId = endId;
    }

    public Float getWeight() {
        return this.weight;
    }

    public void setWeight(Float weight) {
        this.weight = weight;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    public Object getData() {
        return this.data;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    public void setData(Object data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Edges (");

        sb.append(id);
        sb.append(", ").append(uri);
        sb.append(", ").append(relationId);
        sb.append(", ").append(startId);
        sb.append(", ").append(endId);
        sb.append(", ").append(weight);
        sb.append(", ").append(data);

        sb.append(")");
        return sb.toString();
    }
}
