/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.Indexes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.Keys;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.Public;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records.RelationsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relations extends TableImpl<RelationsRecord> {

    private static final long serialVersionUID = -397709598;

    /**
     * The reference instance of <code>public.relations</code>
     */
    public static final Relations RELATIONS = new Relations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelationsRecord> getRecordType() {
        return RelationsRecord.class;
    }

    /**
     * The column <code>public.relations.id</code>.
     */
    public final TableField<RelationsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.relations.uri</code>.
     */
    public final TableField<RelationsRecord, String> URI = createField("uri", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.relations.directed</code>.
     */
    public final TableField<RelationsRecord, Boolean> DIRECTED = createField("directed", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>public.relations</code> table reference
     */
    public Relations() {
        this(DSL.name("relations"), null);
    }

    /**
     * Create an aliased <code>public.relations</code> table reference
     */
    public Relations(String alias) {
        this(DSL.name(alias), RELATIONS);
    }

    /**
     * Create an aliased <code>public.relations</code> table reference
     */
    public Relations(Name alias) {
        this(alias, RELATIONS);
    }

    private Relations(Name alias, Table<RelationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relations(Name alias, Table<RelationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Relations(Table<O> child, ForeignKey<O, RelationsRecord> key) {
        super(child, key, RELATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RELATIONS_PKEY, Indexes.RELATIONS_UNIQUE_URI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RelationsRecord> getPrimaryKey() {
        return Keys.RELATIONS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RelationsRecord>> getKeys() {
        return Arrays.<UniqueKey<RelationsRecord>>asList(Keys.RELATIONS_PKEY, Keys.RELATIONS_UNIQUE_URI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relations as(String alias) {
        return new Relations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relations as(Name alias) {
        return new Relations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Relations rename(String name) {
        return new Relations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Relations rename(Name name) {
        return new Relations(name, null);
    }
}
