/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeSources;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Edges;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.NodePrefixes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Nodes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.RankedFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Relations;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Sources;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.edge_features</code>.
     */
    public static final EdgeFeatures EDGE_FEATURES = EdgeFeatures.EDGE_FEATURES;

    /**
     * The table <code>public.edge_sources</code>.
     */
    public static final EdgeSources EDGE_SOURCES = EdgeSources.EDGE_SOURCES;

    /**
     * The table <code>public.edges</code>.
     */
    public static final Edges EDGES = Edges.EDGES;

    /**
     * The table <code>public.node_prefixes</code>.
     */
    public static final NodePrefixes NODE_PREFIXES = NodePrefixes.NODE_PREFIXES;

    /**
     * The table <code>public.nodes</code>.
     */
    public static final Nodes NODES = Nodes.NODES;

    /**
     * The table <code>public.ranked_features</code>.
     */
    public static final RankedFeatures RANKED_FEATURES = RankedFeatures.RANKED_FEATURES;

    /**
     * The table <code>public.relations</code>.
     */
    public static final Relations RELATIONS = Relations.RELATIONS;

    /**
     * The table <code>public.sources</code>.
     */
    public static final Sources SOURCES = Sources.SOURCES;
}
