/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Entityresolver;
import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityresolverRecord extends TableRecordImpl<EntityresolverRecord> implements Record12<String, String, String, String, String[], String[], String[], String[], String[], String[], String[], String[]> {

    private static final long serialVersionUID = 1057945054;

    /**
     * Setter for <code>public.entityResolver.handle</code>.
     */
    public void setHandle(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.entityResolver.handle</code>.
     */
    public String getHandle() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.entityResolver.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.entityResolver.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.entityResolver.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.entityResolver.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.entityResolver.subtype</code>.
     */
    public void setSubtype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.entityResolver.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.entityResolver.attributes</code>.
     */
    public void setAttributes(String... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.entityResolver.attributes</code>.
     */
    public String[] getAttributes() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.entityResolver.attributes2</code>.
     */
    public void setAttributes2(String... value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.entityResolver.attributes2</code>.
     */
    public String[] getAttributes2() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>public.entityResolver.kbids</code>.
     */
    public void setKbids(String... value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.entityResolver.kbids</code>.
     */
    public String[] getKbids() {
        return (String[]) get(6);
    }

    /**
     * Setter for <code>public.entityResolver.descriptions</code>.
     */
    public void setDescriptions(String... value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.entityResolver.descriptions</code>.
     */
    public String[] getDescriptions() {
        return (String[]) get(7);
    }

    /**
     * Setter for <code>public.entityResolver.justifications</code>.
     */
    public void setJustifications(String... value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.entityResolver.justifications</code>.
     */
    public String[] getJustifications() {
        return (String[]) get(8);
    }

    /**
     * Setter for <code>public.entityResolver.text_strings</code>.
     */
    public void setTextStrings(String... value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.entityResolver.text_strings</code>.
     */
    public String[] getTextStrings() {
        return (String[]) get(9);
    }

    /**
     * Setter for <code>public.entityResolver.ids</code>.
     */
    public void setIds(String... value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.entityResolver.ids</code>.
     */
    public String[] getIds() {
        return (String[]) get(10);
    }

    /**
     * Setter for <code>public.entityResolver.mids</code>.
     */
    public void setMids(String... value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.entityResolver.mids</code>.
     */
    public String[] getMids() {
        return (String[]) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String[], String[], String[], String[], String[], String[], String[], String[]> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String[], String[], String[], String[], String[], String[], String[], String[]> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Entityresolver.ENTITYRESOLVER.HANDLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Entityresolver.ENTITYRESOLVER.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Entityresolver.ENTITYRESOLVER.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Entityresolver.ENTITYRESOLVER.SUBTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field5() {
        return Entityresolver.ENTITYRESOLVER.ATTRIBUTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field6() {
        return Entityresolver.ENTITYRESOLVER.ATTRIBUTES2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field7() {
        return Entityresolver.ENTITYRESOLVER.KBIDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field8() {
        return Entityresolver.ENTITYRESOLVER.DESCRIPTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field9() {
        return Entityresolver.ENTITYRESOLVER.JUSTIFICATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field10() {
        return Entityresolver.ENTITYRESOLVER.TEXT_STRINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field11() {
        return Entityresolver.ENTITYRESOLVER.IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field12() {
        return Entityresolver.ENTITYRESOLVER.MIDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component5() {
        return getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component6() {
        return getAttributes2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component7() {
        return getKbids();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component8() {
        return getDescriptions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component9() {
        return getJustifications();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component10() {
        return getTextStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component11() {
        return getIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component12() {
        return getMids();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value5() {
        return getAttributes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value6() {
        return getAttributes2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value7() {
        return getKbids();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value8() {
        return getDescriptions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value9() {
        return getJustifications();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value10() {
        return getTextStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value11() {
        return getIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value12() {
        return getMids();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value1(String value) {
        setHandle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value2(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value4(String value) {
        setSubtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value5(String... value) {
        setAttributes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value6(String... value) {
        setAttributes2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value7(String... value) {
        setKbids(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value8(String... value) {
        setDescriptions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value9(String... value) {
        setJustifications(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value10(String... value) {
        setTextStrings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value11(String... value) {
        setIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord value12(String... value) {
        setMids(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EntityresolverRecord values(String value1, String value2, String value3, String value4, String[] value5, String[] value6, String[] value7, String[] value8, String[] value9, String[] value10, String[] value11, String[] value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityresolverRecord
     */
    public EntityresolverRecord() {
        super(Entityresolver.ENTITYRESOLVER);
    }

    /**
     * Create a detached, initialised EntityresolverRecord
     */
    public EntityresolverRecord(String handle, String category, String type, String subtype, String[] attributes, String[] attributes2, String[] kbids, String[] descriptions, String[] justifications, String[] textStrings, String[] ids, String[] mids) {
        super(Entityresolver.ENTITYRESOLVER);

        set(0, handle);
        set(1, category);
        set(2, type);
        set(3, subtype);
        set(4, attributes);
        set(5, attributes2);
        set(6, kbids);
        set(7, descriptions);
        set(8, justifications);
        set(9, textStrings);
        set(10, ids);
        set(11, mids);
    }
}
