/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Hypothesis;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypothesisRecord extends TableRecordImpl<HypothesisRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 2093594066;

    /**
     * Setter for <code>public.hypothesis.tree_id</code>.
     */
    public void setTreeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hypothesis.tree_id</code>.
     */
    public String getTreeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.hypothesis.hypothesis_id</code>.
     */
    public void setHypothesisId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hypothesis.hypothesis_id</code>.
     */
    public String getHypothesisId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.hypothesis.mentionId</code>.
     */
    public void setMentionid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hypothesis.mentionId</code>.
     */
    public String getMentionid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.hypothesis.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.hypothesis.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Hypothesis.HYPOTHESIS.TREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Hypothesis.HYPOTHESIS.HYPOTHESIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Hypothesis.HYPOTHESIS.MENTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Hypothesis.HYPOTHESIS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getHypothesisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getHypothesisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypothesisRecord value1(String value) {
        setTreeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypothesisRecord value2(String value) {
        setHypothesisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypothesisRecord value3(String value) {
        setMentionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypothesisRecord value4(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HypothesisRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HypothesisRecord
     */
    public HypothesisRecord() {
        super(Hypothesis.HYPOTHESIS);
    }

    /**
     * Create a detached, initialised HypothesisRecord
     */
    public HypothesisRecord(String treeId, String hypothesisId, String mentionid, String value) {
        super(Hypothesis.HYPOTHESIS);

        set(0, treeId);
        set(1, hypothesisId);
        set(2, mentionid);
        set(3, value);
    }
}
