/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Slot;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlotRecord extends TableRecordImpl<SlotRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1362629983;

    /**
     * Setter for <code>public.slot.tree_id</code>.
     */
    public void setTreeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.slot.tree_id</code>.
     */
    public String getTreeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.slot.mentionId</code>.
     */
    public void setMentionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.slot.mentionId</code>.
     */
    public String getMentionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.slot.slot_type</code>.
     */
    public void setSlotType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.slot.slot_type</code>.
     */
    public String getSlotType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.slot.slot_attribute</code>.
     */
    public void setSlotAttribute(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.slot.slot_attribute</code>.
     */
    public String getSlotAttribute() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.slot.arg_id</code>.
     */
    public void setArgId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.slot.arg_id</code>.
     */
    public String getArgId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Slot.SLOT.TREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Slot.SLOT.MENTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Slot.SLOT.SLOT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Slot.SLOT.SLOT_ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Slot.SLOT.ARG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSlotType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSlotAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getArgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSlotType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSlotAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getArgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord value1(String value) {
        setTreeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord value2(String value) {
        setMentionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord value3(String value) {
        setSlotType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord value4(String value) {
        setSlotAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord value5(String value) {
        setArgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlotRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SlotRecord
     */
    public SlotRecord() {
        super(Slot.SLOT);
    }

    /**
     * Create a detached, initialised SlotRecord
     */
    public SlotRecord(String treeId, String mentionid, String slotType, String slotAttribute, String argId) {
        super(Slot.SLOT);

        set(0, treeId);
        set(1, mentionid);
        set(2, slotType);
        set(3, slotAttribute);
        set(4, argId);
    }
}
