/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables;


import org.ufl.aida.ldc.jOOQ.model.Public;
import org.ufl.aida.ldc.jOOQ.model.tables.records.MentionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mention extends TableImpl<MentionRecord> {

    private static final long serialVersionUID = -590200724;

    /**
     * The reference instance of <code>public.mention</code>
     */
    public static final Mention MENTION = new Mention();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MentionRecord> getRecordType() {
        return MentionRecord.class;
    }

    /**
     * The column <code>public.mention.tree_id</code>.
     */
    public final TableField<MentionRecord, String> TREE_ID = createField("tree_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.mentionId</code>.
     */
    public final TableField<MentionRecord, String> MENTIONID = createField("mentionId", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.id</code>.
     */
    public final TableField<MentionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.provenance</code>.
     */
    public final TableField<MentionRecord, String> PROVENANCE = createField("provenance", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.textoffset_startchar</code>.
     */
    public final TableField<MentionRecord, String> TEXTOFFSET_STARTCHAR = createField("textoffset_startchar", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.textoffset_endchar</code>.
     */
    public final TableField<MentionRecord, String> TEXTOFFSET_ENDCHAR = createField("textoffset_endchar", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.text_string</code>.
     */
    public final TableField<MentionRecord, String> TEXT_STRING = createField("text_string", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.justification</code>.
     */
    public final TableField<MentionRecord, String> JUSTIFICATION = createField("justification", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.type</code>.
     */
    public final TableField<MentionRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.subtype</code>.
     */
    public final TableField<MentionRecord, String> SUBTYPE = createField("subtype", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.attribute</code>.
     */
    public final TableField<MentionRecord, String> ATTRIBUTE = createField("attribute", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.attribute2</code>.
     */
    public final TableField<MentionRecord, String> ATTRIBUTE2 = createField("attribute2", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.start_date_type</code>.
     */
    public final TableField<MentionRecord, String> START_DATE_TYPE = createField("start_date_type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.start_date</code>.
     */
    public final TableField<MentionRecord, String> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.end_date_type</code>.
     */
    public final TableField<MentionRecord, String> END_DATE_TYPE = createField("end_date_type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.end_date</code>.
     */
    public final TableField<MentionRecord, String> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.mention.kb_id</code>.
     */
    public final TableField<MentionRecord, String> KB_ID = createField("kb_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.mention</code> table reference
     */
    public Mention() {
        this(DSL.name("mention"), null);
    }

    /**
     * Create an aliased <code>public.mention</code> table reference
     */
    public Mention(String alias) {
        this(DSL.name(alias), MENTION);
    }

    /**
     * Create an aliased <code>public.mention</code> table reference
     */
    public Mention(Name alias) {
        this(alias, MENTION);
    }

    private Mention(Name alias, Table<MentionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mention(Name alias, Table<MentionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Mention(Table<O> child, ForeignKey<O, MentionRecord> key) {
        super(child, key, MENTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Mention as(String alias) {
        return new Mention(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Mention as(Name alias) {
        return new Mention(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mention rename(String name) {
        return new Mention(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mention rename(Name name) {
        return new Mention(name, null);
    }
}
