/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hypothesis implements Serializable {

    private static final long serialVersionUID = 1864188140;

    private String treeId;
    private String hypothesisId;
    private String mentionid;
    private String value;

    public Hypothesis() {}

    public Hypothesis(Hypothesis value) {
        this.treeId = value.treeId;
        this.hypothesisId = value.hypothesisId;
        this.mentionid = value.mentionid;
        this.value = value.value;
    }

    public Hypothesis(
        String treeId,
        String hypothesisId,
        String mentionid,
        String value
    ) {
        this.treeId = treeId;
        this.hypothesisId = hypothesisId;
        this.mentionid = mentionid;
        this.value = value;
    }

    public String getTreeId() {
        return this.treeId;
    }

    public void setTreeId(String treeId) {
        this.treeId = treeId;
    }

    public String getHypothesisId() {
        return this.hypothesisId;
    }

    public void setHypothesisId(String hypothesisId) {
        this.hypothesisId = hypothesisId;
    }

    public String getMentionid() {
        return this.mentionid;
    }

    public void setMentionid(String mentionid) {
        this.mentionid = mentionid;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Hypothesis (");

        sb.append(treeId);
        sb.append(", ").append(hypothesisId);
        sb.append(", ").append(mentionid);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
