/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.pojos;


import java.util.Arrays;

import javax.annotation.Generated;

import org.ufl.aida.ta2.tables.interfaces.ITuples2;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tuples2 implements ITuples2 {

    private static final long serialVersionUID = 517046803;

    private String   mid;
    private String   nisttype;
    private Double   scoreevent;
    private Boolean  negated;
    private Boolean  hedged;
    private String[] constituent;
    private Object   jsonObjectAgg;

    public Tuples2() {}

    public Tuples2(ITuples2 value) {
        this.mid = value.getMid();
        this.nisttype = value.getNisttype();
        this.scoreevent = value.getScoreevent();
        this.negated = value.getNegated();
        this.hedged = value.getHedged();
        this.constituent = value.getConstituent();
        this.jsonObjectAgg = value.getJsonObjectAgg();
    }

    public Tuples2(
        String   mid,
        String   nisttype,
        Double   scoreevent,
        Boolean  negated,
        Boolean  hedged,
        String[] constituent,
        Object   jsonObjectAgg
    ) {
        this.mid = mid;
        this.nisttype = nisttype;
        this.scoreevent = scoreevent;
        this.negated = negated;
        this.hedged = hedged;
        this.constituent = constituent;
        this.jsonObjectAgg = jsonObjectAgg;
    }

    @Override
    public String getMid() {
        return this.mid;
    }

    @Override
    public void setMid(String mid) {
        this.mid = mid;
    }

    @Override
    public String getNisttype() {
        return this.nisttype;
    }

    @Override
    public void setNisttype(String nisttype) {
        this.nisttype = nisttype;
    }

    @Override
    public Double getScoreevent() {
        return this.scoreevent;
    }

    @Override
    public void setScoreevent(Double scoreevent) {
        this.scoreevent = scoreevent;
    }

    @Override
    public Boolean getNegated() {
        return this.negated;
    }

    @Override
    public void setNegated(Boolean negated) {
        this.negated = negated;
    }

    @Override
    public Boolean getHedged() {
        return this.hedged;
    }

    @Override
    public void setHedged(Boolean hedged) {
        this.hedged = hedged;
    }

    @Override
    public String[] getConstituent() {
        return this.constituent;
    }

    @Override
    public void setConstituent(String... constituent) {
        this.constituent = constituent;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object getJsonObjectAgg() {
        return this.jsonObjectAgg;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    @Override
    public void setJsonObjectAgg(Object jsonObjectAgg) {
        this.jsonObjectAgg = jsonObjectAgg;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tuples2 other = (Tuples2) obj;
        if (mid == null) {
            if (other.mid != null)
                return false;
        }
        else if (!mid.equals(other.mid))
            return false;
        if (nisttype == null) {
            if (other.nisttype != null)
                return false;
        }
        else if (!nisttype.equals(other.nisttype))
            return false;
        if (scoreevent == null) {
            if (other.scoreevent != null)
                return false;
        }
        else if (!scoreevent.equals(other.scoreevent))
            return false;
        if (negated == null) {
            if (other.negated != null)
                return false;
        }
        else if (!negated.equals(other.negated))
            return false;
        if (hedged == null) {
            if (other.hedged != null)
                return false;
        }
        else if (!hedged.equals(other.hedged))
            return false;
        if (constituent == null) {
            if (other.constituent != null)
                return false;
        }
        else if (!Arrays.equals(constituent, other.constituent))
            return false;
        if (jsonObjectAgg == null) {
            if (other.jsonObjectAgg != null)
                return false;
        }
        else if (!jsonObjectAgg.equals(other.jsonObjectAgg))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mid == null) ? 0 : this.mid.hashCode());
        result = prime * result + ((this.nisttype == null) ? 0 : this.nisttype.hashCode());
        result = prime * result + ((this.scoreevent == null) ? 0 : this.scoreevent.hashCode());
        result = prime * result + ((this.negated == null) ? 0 : this.negated.hashCode());
        result = prime * result + ((this.hedged == null) ? 0 : this.hedged.hashCode());
        result = prime * result + ((this.constituent == null) ? 0 : Arrays.hashCode(this.constituent));
        result = prime * result + ((this.jsonObjectAgg == null) ? 0 : this.jsonObjectAgg.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tuples2 (");

        sb.append(mid);
        sb.append(", ").append(nisttype);
        sb.append(", ").append(scoreevent);
        sb.append(", ").append(negated);
        sb.append(", ").append(hedged);
        sb.append(", ").append(Arrays.toString(constituent));
        sb.append(", ").append(jsonObjectAgg);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITuples2 from) {
        setMid(from.getMid());
        setNisttype(from.getNisttype());
        setScoreevent(from.getScoreevent());
        setNegated(from.getNegated());
        setHedged(from.getHedged());
        setConstituent(from.getConstituent());
        setJsonObjectAgg(from.getJsonObjectAgg());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITuples2> E into(E into) {
        into.from(this);
        return into;
    }
}
