/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model;


import org.ufl.aida.ldc.jOOQ.model.tables.Entityresolver;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HANDLESEARCH = Indexes0.HANDLESEARCH;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index HANDLESEARCH = Internal.createIndex("handleSearch", Entityresolver.ENTITYRESOLVER, new OrderField[] { Entityresolver.ENTITYRESOLVER.HANDLE }, false);
    }
}
