/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model;


import org.ufl.aida.ldc.jOOQ.model.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.entityResolver</code>.
     */
    public static final Entityresolver ENTITYRESOLVER = Entityresolver.ENTITYRESOLVER;

    /**
     * The table <code>public.hypothesis</code>.
     */
    public static final Hypothesis HYPOTHESIS = Hypothesis.HYPOTHESIS;

    /**
     * The table <code>public.linkedmentions</code>.
     */
    public static final Linkedmentions LINKEDMENTIONS = Linkedmentions.LINKEDMENTIONS;

    /**
     * The table <code>public.mention</code>.
     */
    public static final Mention MENTION = Mention.MENTION;

    /**
     * The table <code>public.mentionslot</code>.
     */
    public static final Mentionslot MENTIONSLOT = Mentionslot.MENTIONSLOT;

    /**
     * The table <code>public.miniKB</code>.
     */
    public static final Minikb MINIKB = Minikb.MINIKB;

    /**
     * The table <code>public.slot</code>.
     */
    public static final Slot SLOT = Slot.SLOT;
}
