/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.daos;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Nodes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records.NodesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NodesDao extends DAOImpl<NodesRecord, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes, Integer> {

    /**
     * Create a new NodesDao without any configuration
     */
    public NodesDao() {
        super(Nodes.NODES, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes.class);
    }

    /**
     * Create a new NodesDao with an attached configuration
     */
    public NodesDao(Configuration configuration) {
        super(Nodes.NODES, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes> fetchById(Integer... values) {
        return fetch(Nodes.NODES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes fetchOneById(Integer value) {
        return fetchOne(Nodes.NODES.ID, value);
    }

    /**
     * Fetch records that have <code>uri IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes> fetchByUri(String... values) {
        return fetch(Nodes.NODES.URI, values);
    }

    /**
     * Fetch a unique record that has <code>uri = value</code>
     */
    public org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Nodes fetchOneByUri(String value) {
        return fetchOne(Nodes.NODES.URI, value);
    }
}
