/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeSources;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Edges;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.NodePrefixes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Nodes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.RankedFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Relations;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Sources;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EF_FEATURE = Indexes0.EF_FEATURE;
    public static final Index EF_NODE = Indexes0.EF_NODE;
    public static final Index EDGE_SOURCES_UNIQUE = Indexes0.EDGE_SOURCES_UNIQUE;
    public static final Index ES_EDGE = Indexes0.ES_EDGE;
    public static final Index ES_SOURCE = Indexes0.ES_SOURCE;
    public static final Index EDGE_END = Indexes0.EDGE_END;
    public static final Index EDGE_RELATION = Indexes0.EDGE_RELATION;
    public static final Index EDGE_START = Indexes0.EDGE_START;
    public static final Index EDGE_WEIGHT = Indexes0.EDGE_WEIGHT;
    public static final Index EDGES_PKEY = Indexes0.EDGES_PKEY;
    public static final Index EDGES_UNIQUE_URI = Indexes0.EDGES_UNIQUE_URI;
    public static final Index NODE_PREFIXES_UNIQUE = Indexes0.NODE_PREFIXES_UNIQUE;
    public static final Index NP_PREFIX = Indexes0.NP_PREFIX;
    public static final Index NODES_PKEY = Indexes0.NODES_PKEY;
    public static final Index NODES_UNIQUE_URI = Indexes0.NODES_UNIQUE_URI;
    public static final Index RF_NODE = Indexes0.RF_NODE;
    public static final Index RELATIONS_PKEY = Indexes0.RELATIONS_PKEY;
    public static final Index RELATIONS_UNIQUE_URI = Indexes0.RELATIONS_UNIQUE_URI;
    public static final Index SOURCES_PKEY = Indexes0.SOURCES_PKEY;
    public static final Index SOURCES_UNIQUE_URI = Indexes0.SOURCES_UNIQUE_URI;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EF_FEATURE = Internal.createIndex("ef_feature", EdgeFeatures.EDGE_FEATURES, new OrderField[] { EdgeFeatures.EDGE_FEATURES.REL_ID, EdgeFeatures.EDGE_FEATURES.DIRECTION, EdgeFeatures.EDGE_FEATURES.NODE_ID }, false);
        public static Index EF_NODE = Internal.createIndex("ef_node", EdgeFeatures.EDGE_FEATURES, new OrderField[] { EdgeFeatures.EDGE_FEATURES.NODE_ID }, false);
        public static Index EDGE_SOURCES_UNIQUE = Internal.createIndex("edge_sources_unique", EdgeSources.EDGE_SOURCES, new OrderField[] { EdgeSources.EDGE_SOURCES.EDGE_ID, EdgeSources.EDGE_SOURCES.SOURCE_ID }, true);
        public static Index ES_EDGE = Internal.createIndex("es_edge", EdgeSources.EDGE_SOURCES, new OrderField[] { EdgeSources.EDGE_SOURCES.EDGE_ID }, false);
        public static Index ES_SOURCE = Internal.createIndex("es_source", EdgeSources.EDGE_SOURCES, new OrderField[] { EdgeSources.EDGE_SOURCES.SOURCE_ID }, false);
        public static Index EDGE_END = Internal.createIndex("edge_end", Edges.EDGES, new OrderField[] { Edges.EDGES.END_ID }, false);
        public static Index EDGE_RELATION = Internal.createIndex("edge_relation", Edges.EDGES, new OrderField[] { Edges.EDGES.RELATION_ID }, false);
        public static Index EDGE_START = Internal.createIndex("edge_start", Edges.EDGES, new OrderField[] { Edges.EDGES.START_ID }, false);
        public static Index EDGE_WEIGHT = Internal.createIndex("edge_weight", Edges.EDGES, new OrderField[] { Edges.EDGES.WEIGHT }, false);
        public static Index EDGES_PKEY = Internal.createIndex("edges_pkey", Edges.EDGES, new OrderField[] { Edges.EDGES.ID }, true);
        public static Index EDGES_UNIQUE_URI = Internal.createIndex("edges_unique_uri", Edges.EDGES, new OrderField[] { Edges.EDGES.URI }, true);
        public static Index NODE_PREFIXES_UNIQUE = Internal.createIndex("node_prefixes_unique", NodePrefixes.NODE_PREFIXES, new OrderField[] { NodePrefixes.NODE_PREFIXES.NODE_ID, NodePrefixes.NODE_PREFIXES.PREFIX_ID }, true);
        public static Index NP_PREFIX = Internal.createIndex("np_prefix", NodePrefixes.NODE_PREFIXES, new OrderField[] { NodePrefixes.NODE_PREFIXES.PREFIX_ID }, false);
        public static Index NODES_PKEY = Internal.createIndex("nodes_pkey", Nodes.NODES, new OrderField[] { Nodes.NODES.ID }, true);
        public static Index NODES_UNIQUE_URI = Internal.createIndex("nodes_unique_uri", Nodes.NODES, new OrderField[] { Nodes.NODES.URI }, true);
        public static Index RF_NODE = Internal.createIndex("rf_node", RankedFeatures.RANKED_FEATURES, new OrderField[] { RankedFeatures.RANKED_FEATURES.NODE_ID }, false);
        public static Index RELATIONS_PKEY = Internal.createIndex("relations_pkey", Relations.RELATIONS, new OrderField[] { Relations.RELATIONS.ID }, true);
        public static Index RELATIONS_UNIQUE_URI = Internal.createIndex("relations_unique_uri", Relations.RELATIONS, new OrderField[] { Relations.RELATIONS.URI }, true);
        public static Index SOURCES_PKEY = Internal.createIndex("sources_pkey", Sources.SOURCES, new OrderField[] { Sources.SOURCES.ID }, true);
        public static Index SOURCES_UNIQUE_URI = Internal.createIndex("sources_unique_uri", Sources.SOURCES, new OrderField[] { Sources.SOURCES.URI }, true);
    }
}
