/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.EdgeSources;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Edges;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.NodePrefixes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Nodes;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.RankedFeatures;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Relations;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Sources;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1400412959;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.edge_features</code>.
     */
    public final EdgeFeatures EDGE_FEATURES = EdgeFeatures.EDGE_FEATURES;

    /**
     * The table <code>public.edge_sources</code>.
     */
    public final EdgeSources EDGE_SOURCES = EdgeSources.EDGE_SOURCES;

    /**
     * The table <code>public.edges</code>.
     */
    public final Edges EDGES = Edges.EDGES;

    /**
     * The table <code>public.node_prefixes</code>.
     */
    public final NodePrefixes NODE_PREFIXES = NodePrefixes.NODE_PREFIXES;

    /**
     * The table <code>public.nodes</code>.
     */
    public final Nodes NODES = Nodes.NODES;

    /**
     * The table <code>public.ranked_features</code>.
     */
    public final RankedFeatures RANKED_FEATURES = RankedFeatures.RANKED_FEATURES;

    /**
     * The table <code>public.relations</code>.
     */
    public final Relations RELATIONS = Relations.RELATIONS;

    /**
     * The table <code>public.sources</code>.
     */
    public final Sources SOURCES = Sources.SOURCES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            EdgeFeatures.EDGE_FEATURES,
            EdgeSources.EDGE_SOURCES,
            Edges.EDGES,
            NodePrefixes.NODE_PREFIXES,
            Nodes.NODES,
            RankedFeatures.RANKED_FEATURES,
            Relations.RELATIONS,
            Sources.SOURCES);
    }
}
