/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2;


import javax.annotation.Generated;

import org.ufl.aida.ta2.tables.Fact;
import org.ufl.aida.ta2.tables.MentionsForUpdate;
import org.ufl.aida.ta2.tables.Tuples;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.fact</code>.
     */
    public static final Fact FACT = org.ufl.aida.ta2.tables.Fact.FACT;

    /**
     * The table <code>public.mentions_for_update</code>.
     */
    public static final MentionsForUpdate MENTIONS_FOR_UPDATE = org.ufl.aida.ta2.tables.MentionsForUpdate.MENTIONS_FOR_UPDATE;

    /**
     * The table <code>public.tuples</code>.
     */
    public static final Tuples TUPLES = org.ufl.aida.ta2.tables.Tuples.TUPLES;
}
