/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.pojos;


import java.util.Arrays;

import javax.annotation.Generated;

import org.ufl.aida.ta2.tables.interfaces.ITuples;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tuples implements ITuples {

    private static final long serialVersionUID = -794773818;

    private String   nisttype;
    private String   mid;
    private Object[] arrayAgg;

    public Tuples() {}

    public Tuples(ITuples value) {
        this.nisttype = value.getNisttype();
        this.mid = value.getMid();
        this.arrayAgg = value.getArrayAgg();
    }

    public Tuples(
        String   nisttype,
        String   mid,
        Object[] arrayAgg
    ) {
        this.nisttype = nisttype;
        this.mid = mid;
        this.arrayAgg = arrayAgg;
    }

    @Override
    public String getNisttype() {
        return this.nisttype;
    }

    @Override
    public void setNisttype(String nisttype) {
        this.nisttype = nisttype;
    }

    @Override
    public String getMid() {
        return this.mid;
    }

    @Override
    public void setMid(String mid) {
        this.mid = mid;
    }

    @Override
    public Object[] getArrayAgg() {
        return this.arrayAgg;
    }

    @Override
    public void setArrayAgg(Object... arrayAgg) {
        this.arrayAgg = arrayAgg;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tuples other = (Tuples) obj;
        if (nisttype == null) {
            if (other.nisttype != null)
                return false;
        }
        else if (!nisttype.equals(other.nisttype))
            return false;
        if (mid == null) {
            if (other.mid != null)
                return false;
        }
        else if (!mid.equals(other.mid))
            return false;
        if (arrayAgg == null) {
            if (other.arrayAgg != null)
                return false;
        }
        else if (!Arrays.equals(arrayAgg, other.arrayAgg))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.nisttype == null) ? 0 : this.nisttype.hashCode());
        result = prime * result + ((this.mid == null) ? 0 : this.mid.hashCode());
        result = prime * result + ((this.arrayAgg == null) ? 0 : Arrays.hashCode(this.arrayAgg));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tuples (");

        sb.append(nisttype);
        sb.append(", ").append(mid);
        sb.append(", ").append(Arrays.toString(arrayAgg));

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITuples from) {
        setNisttype(from.getNisttype());
        setMid(from.getMid());
        setArrayAgg(from.getArrayAgg());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITuples> E into(E into) {
        into.from(this);
        return into;
    }
}
