/*
 * This file is generated by jOOQ.
 */
package org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.daos;


import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.Edges;
import org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.records.EdgesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdgesDao extends DAOImpl<EdgesRecord, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges, Integer> {

    /**
     * Create a new EdgesDao without any configuration
     */
    public EdgesDao() {
        super(Edges.EDGES, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges.class);
    }

    /**
     * Create a new EdgesDao with an attached configuration
     */
    public EdgesDao(Configuration configuration) {
        super(Edges.EDGES, org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchById(Integer... values) {
        return fetch(Edges.EDGES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges fetchOneById(Integer value) {
        return fetchOne(Edges.EDGES.ID, value);
    }

    /**
     * Fetch records that have <code>uri IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByUri(String... values) {
        return fetch(Edges.EDGES.URI, values);
    }

    /**
     * Fetch a unique record that has <code>uri = value</code>
     */
    public org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges fetchOneByUri(String value) {
        return fetchOne(Edges.EDGES.URI, value);
    }

    /**
     * Fetch records that have <code>relation_id IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByRelationId(Integer... values) {
        return fetch(Edges.EDGES.RELATION_ID, values);
    }

    /**
     * Fetch records that have <code>start_id IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByStartId(Integer... values) {
        return fetch(Edges.EDGES.START_ID, values);
    }

    /**
     * Fetch records that have <code>end_id IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByEndId(Integer... values) {
        return fetch(Edges.EDGES.END_ID, values);
    }

    /**
     * Fetch records that have <code>weight IN (values)</code>
     */
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByWeight(Float... values) {
        return fetch(Edges.EDGES.WEIGHT, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @Deprecated
    public List<org.ufl.hypogator.jackb.traversers.conceptnet.jOOQ.model.tables.pojos.Edges> fetchByData(Object... values) {
        return fetch(Edges.EDGES.DATA, values);
    }
}
