/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Linkedmentions;
import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkedmentionsRecord extends TableRecordImpl<LinkedmentionsRecord> implements Record21<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -930273307;

    /**
     * Setter for <code>public.linkedmentions.tree_id</code>.
     */
    public void setTreeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.linkedmentions.tree_id</code>.
     */
    public String getTreeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.linkedmentions.mentionId</code>.
     */
    public void setMentionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.linkedmentions.mentionId</code>.
     */
    public String getMentionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.linkedmentions.id</code>.
     */
    public void setId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.linkedmentions.id</code>.
     */
    public String getId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.linkedmentions.provenance</code>.
     */
    public void setProvenance(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.linkedmentions.provenance</code>.
     */
    public String getProvenance() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.linkedmentions.handle</code>.
     */
    public void setHandle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.linkedmentions.handle</code>.
     */
    public String getHandle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.linkedmentions.text_string</code>.
     */
    public void setTextString(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.linkedmentions.text_string</code>.
     */
    public String getTextString() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.linkedmentions.justification</code>.
     */
    public void setJustification(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.linkedmentions.justification</code>.
     */
    public String getJustification() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.linkedmentions.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.linkedmentions.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.linkedmentions.category</code>.
     */
    public void setCategory(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.linkedmentions.category</code>.
     */
    public String getCategory() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.linkedmentions.type</code>.
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.linkedmentions.type</code>.
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.linkedmentions.subtype</code>.
     */
    public void setSubtype(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.linkedmentions.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.linkedmentions.attribute</code>.
     */
    public void setAttribute(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.linkedmentions.attribute</code>.
     */
    public String getAttribute() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.linkedmentions.attribute2</code>.
     */
    public void setAttribute2(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.linkedmentions.attribute2</code>.
     */
    public String getAttribute2() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.linkedmentions.start_date_type</code>.
     */
    public void setStartDateType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.linkedmentions.start_date_type</code>.
     */
    public String getStartDateType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.linkedmentions.start_date</code>.
     */
    public void setStartDate(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.linkedmentions.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.linkedmentions.end_date_type</code>.
     */
    public void setEndDateType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.linkedmentions.end_date_type</code>.
     */
    public String getEndDateType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.linkedmentions.end_date</code>.
     */
    public void setEndDate(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.linkedmentions.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.linkedmentions.kb_id</code>.
     */
    public void setKbId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.linkedmentions.kb_id</code>.
     */
    public String getKbId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.linkedmentions.topic_id</code>.
     */
    public void setTopicId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.linkedmentions.topic_id</code>.
     */
    public String getTopicId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.linkedmentions.textoffset_startchar</code>.
     */
    public void setTextoffsetStartchar(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.linkedmentions.textoffset_startchar</code>.
     */
    public String getTextoffsetStartchar() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.linkedmentions.textoffset_endchar</code>.
     */
    public void setTextoffsetEndchar(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.linkedmentions.textoffset_endchar</code>.
     */
    public String getTextoffsetEndchar() {
        return (String) get(20);
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Linkedmentions.LINKEDMENTIONS.TREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Linkedmentions.LINKEDMENTIONS.MENTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Linkedmentions.LINKEDMENTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Linkedmentions.LINKEDMENTIONS.PROVENANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Linkedmentions.LINKEDMENTIONS.HANDLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Linkedmentions.LINKEDMENTIONS.TEXT_STRING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Linkedmentions.LINKEDMENTIONS.JUSTIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Linkedmentions.LINKEDMENTIONS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Linkedmentions.LINKEDMENTIONS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Linkedmentions.LINKEDMENTIONS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Linkedmentions.LINKEDMENTIONS.SUBTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Linkedmentions.LINKEDMENTIONS.ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Linkedmentions.LINKEDMENTIONS.ATTRIBUTE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Linkedmentions.LINKEDMENTIONS.START_DATE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Linkedmentions.LINKEDMENTIONS.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Linkedmentions.LINKEDMENTIONS.END_DATE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Linkedmentions.LINKEDMENTIONS.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Linkedmentions.LINKEDMENTIONS.KB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Linkedmentions.LINKEDMENTIONS.TOPIC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Linkedmentions.LINKEDMENTIONS.TEXTOFFSET_STARTCHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return Linkedmentions.LINKEDMENTIONS.TEXTOFFSET_ENDCHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProvenance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTextString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getJustification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAttribute2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getStartDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getEndDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getTextoffsetStartchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component21() {
        return getTextoffsetEndchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProvenance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTextString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getJustification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAttribute2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getStartDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getEndDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getTextoffsetStartchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getTextoffsetEndchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value1(String value) {
        setTreeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value2(String value) {
        setMentionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value3(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value4(String value) {
        setProvenance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value5(String value) {
        setHandle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value6(String value) {
        setTextString(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value7(String value) {
        setJustification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value8(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value9(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value10(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value11(String value) {
        setSubtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value12(String value) {
        setAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value13(String value) {
        setAttribute2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value14(String value) {
        setStartDateType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value15(String value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value16(String value) {
        setEndDateType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value17(String value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value18(String value) {
        setKbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value19(String value) {
        setTopicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value20(String value) {
        setTextoffsetStartchar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord value21(String value) {
        setTextoffsetEndchar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LinkedmentionsRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, String value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkedmentionsRecord
     */
    public LinkedmentionsRecord() {
        super(Linkedmentions.LINKEDMENTIONS);
    }

    /**
     * Create a detached, initialised LinkedmentionsRecord
     */
    public LinkedmentionsRecord(String treeId, String mentionid, String id, String provenance, String handle, String textString, String justification, String description, String category, String type, String subtype, String attribute, String attribute2, String startDateType, String startDate, String endDateType, String endDate, String kbId, String topicId, String textoffsetStartchar, String textoffsetEndchar) {
        super(Linkedmentions.LINKEDMENTIONS);

        set(0, treeId);
        set(1, mentionid);
        set(2, id);
        set(3, provenance);
        set(4, handle);
        set(5, textString);
        set(6, justification);
        set(7, description);
        set(8, category);
        set(9, type);
        set(10, subtype);
        set(11, attribute);
        set(12, attribute2);
        set(13, startDateType);
        set(14, startDate);
        set(15, endDateType);
        set(16, endDate);
        set(17, kbId);
        set(18, topicId);
        set(19, textoffsetStartchar);
        set(20, textoffsetEndchar);
    }
}
