/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Mention;
import org.jooq.Field;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MentionRecord extends TableRecordImpl<MentionRecord> implements Record17<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 280116371;

    /**
     * Setter for <code>public.mention.tree_id</code>.
     */
    public void setTreeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mention.tree_id</code>.
     */
    public String getTreeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.mention.mentionId</code>.
     */
    public void setMentionid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mention.mentionId</code>.
     */
    public String getMentionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mention.id</code>.
     */
    public void setId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mention.id</code>.
     */
    public String getId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mention.provenance</code>.
     */
    public void setProvenance(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mention.provenance</code>.
     */
    public String getProvenance() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mention.textoffset_startchar</code>.
     */
    public void setTextoffsetStartchar(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mention.textoffset_startchar</code>.
     */
    public String getTextoffsetStartchar() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mention.textoffset_endchar</code>.
     */
    public void setTextoffsetEndchar(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mention.textoffset_endchar</code>.
     */
    public String getTextoffsetEndchar() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mention.text_string</code>.
     */
    public void setTextString(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mention.text_string</code>.
     */
    public String getTextString() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mention.justification</code>.
     */
    public void setJustification(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mention.justification</code>.
     */
    public String getJustification() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mention.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mention.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mention.subtype</code>.
     */
    public void setSubtype(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mention.subtype</code>.
     */
    public String getSubtype() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mention.attribute</code>.
     */
    public void setAttribute(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mention.attribute</code>.
     */
    public String getAttribute() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mention.attribute2</code>.
     */
    public void setAttribute2(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mention.attribute2</code>.
     */
    public String getAttribute2() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mention.start_date_type</code>.
     */
    public void setStartDateType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mention.start_date_type</code>.
     */
    public String getStartDateType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.mention.start_date</code>.
     */
    public void setStartDate(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mention.start_date</code>.
     */
    public String getStartDate() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.mention.end_date_type</code>.
     */
    public void setEndDateType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mention.end_date_type</code>.
     */
    public String getEndDateType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.mention.end_date</code>.
     */
    public void setEndDate(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mention.end_date</code>.
     */
    public String getEndDate() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.mention.kb_id</code>.
     */
    public void setKbId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.mention.kb_id</code>.
     */
    public String getKbId() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Mention.MENTION.TREE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mention.MENTION.MENTIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Mention.MENTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mention.MENTION.PROVENANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Mention.MENTION.TEXTOFFSET_STARTCHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Mention.MENTION.TEXTOFFSET_ENDCHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Mention.MENTION.TEXT_STRING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Mention.MENTION.JUSTIFICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Mention.MENTION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Mention.MENTION.SUBTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Mention.MENTION.ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Mention.MENTION.ATTRIBUTE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Mention.MENTION.START_DATE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Mention.MENTION.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Mention.MENTION.END_DATE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Mention.MENTION.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Mention.MENTION.KB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProvenance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTextoffsetStartchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTextoffsetEndchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTextString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getJustification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAttribute2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getStartDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getEndDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTreeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMentionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProvenance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTextoffsetStartchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTextoffsetEndchar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTextString();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getJustification();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSubtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAttribute2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getStartDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getEndDateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value1(String value) {
        setTreeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value2(String value) {
        setMentionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value3(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value4(String value) {
        setProvenance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value5(String value) {
        setTextoffsetStartchar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value6(String value) {
        setTextoffsetEndchar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value7(String value) {
        setTextString(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value8(String value) {
        setJustification(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value9(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value10(String value) {
        setSubtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value11(String value) {
        setAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value12(String value) {
        setAttribute2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value13(String value) {
        setStartDateType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value14(String value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value15(String value) {
        setEndDateType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value16(String value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord value17(String value) {
        setKbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MentionRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MentionRecord
     */
    public MentionRecord() {
        super(Mention.MENTION);
    }

    /**
     * Create a detached, initialised MentionRecord
     */
    public MentionRecord(String treeId, String mentionid, String id, String provenance, String textoffsetStartchar, String textoffsetEndchar, String textString, String justification, String type, String subtype, String attribute, String attribute2, String startDateType, String startDate, String endDateType, String endDate, String kbId) {
        super(Mention.MENTION);

        set(0, treeId);
        set(1, mentionid);
        set(2, id);
        set(3, provenance);
        set(4, textoffsetStartchar);
        set(5, textoffsetEndchar);
        set(6, textString);
        set(7, justification);
        set(8, type);
        set(9, subtype);
        set(10, attribute);
        set(11, attribute2);
        set(12, startDateType);
        set(13, startDate);
        set(14, endDateType);
        set(15, endDate);
        set(16, kbId);
    }
}
