/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ldc.jOOQ.model.tables.records;


import org.ufl.aida.ldc.jOOQ.model.tables.Minikb;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinikbRecord extends TableRecordImpl<MinikbRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = -1324201731;

    /**
     * Setter for <code>public.miniKB.kb_id</code>.
     */
    public void setKbId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.miniKB.kb_id</code>.
     */
    public String getKbId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.miniKB.topic_id</code>.
     */
    public void setTopicId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.miniKB.topic_id</code>.
     */
    public String getTopicId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.miniKB.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.miniKB.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.miniKB.handle</code>.
     */
    public void setHandle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.miniKB.handle</code>.
     */
    public String getHandle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.miniKB.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.miniKB.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Minikb.MINIKB.KB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Minikb.MINIKB.TOPIC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Minikb.MINIKB.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Minikb.MINIKB.HANDLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Minikb.MINIKB.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord value1(String value) {
        setKbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord value2(String value) {
        setTopicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord value3(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord value4(String value) {
        setHandle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinikbRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MinikbRecord
     */
    public MinikbRecord() {
        super(Minikb.MINIKB);
    }

    /**
     * Create a detached, initialised MinikbRecord
     */
    public MinikbRecord(String kbId, String topicId, String category, String handle, String description) {
        super(Minikb.MINIKB);

        set(0, kbId);
        set(1, topicId);
        set(2, category);
        set(3, handle);
        set(4, description);
    }
}
