/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFact extends Serializable {

    /**
     * Setter for <code>public.fact.mid</code>.
     */
    public void setMid(String value);

    /**
     * Getter for <code>public.fact.mid</code>.
     */
    public String getMid();

    /**
     * Setter for <code>public.fact.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>public.fact.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.fact.nistTypeLeft</code>.
     */
    public void setNisttypeleft(String value);

    /**
     * Getter for <code>public.fact.nistTypeLeft</code>.
     */
    public String getNisttypeleft();

    /**
     * Setter for <code>public.fact.nistTypeRight</code>.
     */
    public void setNisttyperight(String value);

    /**
     * Getter for <code>public.fact.nistTypeRight</code>.
     */
    public String getNisttyperight();

    /**
     * Setter for <code>public.fact.nistType</code>.
     */
    public void setNisttype(String value);

    /**
     * Getter for <code>public.fact.nistType</code>.
     */
    public String getNisttype();

    /**
     * Setter for <code>public.fact.tree_id</code>.
     */
    public void setTreeId(String value);

    /**
     * Getter for <code>public.fact.tree_id</code>.
     */
    public String getTreeId();

    /**
     * Setter for <code>public.fact.partialLabel</code>.
     */
    public void setPartiallabel(String value);

    /**
     * Getter for <code>public.fact.partialLabel</code>.
     */
    public String getPartiallabel();

    /**
     * Setter for <code>public.fact.nistFullLabel</code>.
     */
    public void setNistfulllabel(String value);

    /**
     * Getter for <code>public.fact.nistFullLabel</code>.
     */
    public String getNistfulllabel();

    /**
     * Setter for <code>public.fact.argumentId</code>.
     */
    public void setArgumentid(String value);

    /**
     * Getter for <code>public.fact.argumentId</code>.
     */
    public String getArgumentid();

    /**
     * Setter for <code>public.fact.argumentNistType</code>.
     */
    public void setArgumentnisttype(String value);

    /**
     * Getter for <code>public.fact.argumentNistType</code>.
     */
    public String getArgumentnisttype();

    /**
     * Setter for <code>public.fact.argumentRawString</code>.
     */
    public void setArgumentrawstring(String value);

    /**
     * Getter for <code>public.fact.argumentRawString</code>.
     */
    public String getArgumentrawstring();

    /**
     * Setter for <code>public.fact.argumentClusterId</code>.
     */
    public void setArgumentclusterid(String value);

    /**
     * Getter for <code>public.fact.argumentClusterId</code>.
     */
    public String getArgumentclusterid();

    /**
     * Setter for <code>public.fact.argumentBadlyTranslatedString</code>.
     */
    public void setArgumentbadlytranslatedstring(String value);

    /**
     * Getter for <code>public.fact.argumentBadlyTranslatedString</code>.
     */
    public String getArgumentbadlytranslatedstring();

    /**
     * Setter for <code>public.fact.rKind</code>.
     */
    public void setRkind(String value);

    /**
     * Getter for <code>public.fact.rKind</code>.
     */
    public String getRkind();

    /**
     * Setter for <code>public.fact.rNistName</code>.
     */
    public void setRnistname(String value);

    /**
     * Getter for <code>public.fact.rNistName</code>.
     */
    public String getRnistname();

    /**
     * Setter for <code>public.fact.resolvedName</code>.
     */
    public void setResolvedname(String value);

    /**
     * Getter for <code>public.fact.resolvedName</code>.
     */
    public String getResolvedname();

    /**
     * Setter for <code>public.fact.resolvedType</code>.
     */
    public void setResolvedtype(String value);

    /**
     * Getter for <code>public.fact.resolvedType</code>.
     */
    public String getResolvedtype();

    /**
     * Setter for <code>public.fact.score</code>.
     */
    public void setScore(Double value);

    /**
     * Getter for <code>public.fact.score</code>.
     */
    public Double getScore();

    /**
     * Setter for <code>public.fact.fromFuzzyMatching</code>.
     */
    public void setFromfuzzymatching(Boolean value);

    /**
     * Getter for <code>public.fact.fromFuzzyMatching</code>.
     */
    public Boolean getFromfuzzymatching();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFact
     */
    public void from(org.ufl.aida.ta2.tables.interfaces.IFact from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFact
     */
    public <E extends org.ufl.aida.ta2.tables.interfaces.IFact> E into(E into);
}
