/*
 * This file is generated by jOOQ.
 */
package org.ufl.aida.ta2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITuples extends Serializable {

    /**
     * Setter for <code>public.tuples.nistType</code>.
     */
    public void setNisttype(String value);

    /**
     * Getter for <code>public.tuples.nistType</code>.
     */
    public String getNisttype();

    /**
     * Setter for <code>public.tuples.mid</code>.
     */
    public void setMid(String value);

    /**
     * Getter for <code>public.tuples.mid</code>.
     */
    public String getMid();

    /**
     * Setter for <code>public.tuples.array_agg</code>.
     */
    public void setArrayAgg(Object... value);

    /**
     * Getter for <code>public.tuples.array_agg</code>.
     */
    public Object[] getArrayAgg();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITuples
     */
    public void from(org.ufl.aida.ta2.tables.interfaces.ITuples from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITuples
     */
    public <E extends org.ufl.aida.ta2.tables.interfaces.ITuples> E into(E into);
}
